/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcProductField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcProductField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcProductField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcProductField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductID(String value) {
    riskuserapiJNI.CShfeFtdcProductField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return riskuserapiJNI.CShfeFtdcProductField_ProductID_get(swigCPtr, this);
  }

  public void setProductName(String value) {
    riskuserapiJNI.CShfeFtdcProductField_ProductName_set(swigCPtr, this, value);
  }

  public String getProductName() {
    return riskuserapiJNI.CShfeFtdcProductField_ProductName_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcProductField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcProductField_ExchangeID_get(swigCPtr, this);
  }

  public void setProductClass(char value) {
    riskuserapiJNI.CShfeFtdcProductField_ProductClass_set(swigCPtr, this, value);
  }

  public char getProductClass() {
    return riskuserapiJNI.CShfeFtdcProductField_ProductClass_get(swigCPtr, this);
  }

  public void setVolumeMultiple(int value) {
    riskuserapiJNI.CShfeFtdcProductField_VolumeMultiple_set(swigCPtr, this, value);
  }

  public int getVolumeMultiple() {
    return riskuserapiJNI.CShfeFtdcProductField_VolumeMultiple_get(swigCPtr, this);
  }

  public void setPriceTick(double value) {
    riskuserapiJNI.CShfeFtdcProductField_PriceTick_set(swigCPtr, this, value);
  }

  public double getPriceTick() {
    return riskuserapiJNI.CShfeFtdcProductField_PriceTick_get(swigCPtr, this);
  }

  public void setMaxMarketOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcProductField_MaxMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxMarketOrderVolume() {
    return riskuserapiJNI.CShfeFtdcProductField_MaxMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMinMarketOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcProductField_MinMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinMarketOrderVolume() {
    return riskuserapiJNI.CShfeFtdcProductField_MinMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMaxLimitOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcProductField_MaxLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxLimitOrderVolume() {
    return riskuserapiJNI.CShfeFtdcProductField_MaxLimitOrderVolume_get(swigCPtr, this);
  }

  public void setMinLimitOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcProductField_MinLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinLimitOrderVolume() {
    return riskuserapiJNI.CShfeFtdcProductField_MinLimitOrderVolume_get(swigCPtr, this);
  }

  public void setPositionType(char value) {
    riskuserapiJNI.CShfeFtdcProductField_PositionType_set(swigCPtr, this, value);
  }

  public char getPositionType() {
    return riskuserapiJNI.CShfeFtdcProductField_PositionType_get(swigCPtr, this);
  }

  public void setPositionDateType(char value) {
    riskuserapiJNI.CShfeFtdcProductField_PositionDateType_set(swigCPtr, this, value);
  }

  public char getPositionDateType() {
    return riskuserapiJNI.CShfeFtdcProductField_PositionDateType_get(swigCPtr, this);
  }

  public void setCloseDealType(char value) {
    riskuserapiJNI.CShfeFtdcProductField_CloseDealType_set(swigCPtr, this, value);
  }

  public char getCloseDealType() {
    return riskuserapiJNI.CShfeFtdcProductField_CloseDealType_get(swigCPtr, this);
  }

  public void setTradeCurrencyID(String value) {
    riskuserapiJNI.CShfeFtdcProductField_TradeCurrencyID_set(swigCPtr, this, value);
  }

  public String getTradeCurrencyID() {
    return riskuserapiJNI.CShfeFtdcProductField_TradeCurrencyID_get(swigCPtr, this);
  }

  public void setMortgageFundUseRange(char value) {
    riskuserapiJNI.CShfeFtdcProductField_MortgageFundUseRange_set(swigCPtr, this, value);
  }

  public char getMortgageFundUseRange() {
    return riskuserapiJNI.CShfeFtdcProductField_MortgageFundUseRange_get(swigCPtr, this);
  }

  public void setExchangeProductID(String value) {
    riskuserapiJNI.CShfeFtdcProductField_ExchangeProductID_set(swigCPtr, this, value);
  }

  public String getExchangeProductID() {
    return riskuserapiJNI.CShfeFtdcProductField_ExchangeProductID_get(swigCPtr, this);
  }

  public void setUnderlyingMultiple(double value) {
    riskuserapiJNI.CShfeFtdcProductField_UnderlyingMultiple_set(swigCPtr, this, value);
  }

  public double getUnderlyingMultiple() {
    return riskuserapiJNI.CShfeFtdcProductField_UnderlyingMultiple_get(swigCPtr, this);
  }

  public CShfeFtdcProductField() {
    this(riskuserapiJNI.new_CShfeFtdcProductField(), true);
  }

}
