/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcNoticePatternField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcNoticePatternField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcNoticePatternField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcNoticePatternField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_BrokerID_get(swigCPtr, this);
  }

  public void setBizType(String value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_BizType_set(swigCPtr, this, value);
  }

  public String getBizType() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_BizType_get(swigCPtr, this);
  }

  public void setMethod(char value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_Method_set(swigCPtr, this, value);
  }

  public char getMethod() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_Method_get(swigCPtr, this);
  }

  public void setBizName(String value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_BizName_set(swigCPtr, this, value);
  }

  public String getBizName() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_BizName_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_UserID_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_IsActive_get(swigCPtr, this);
  }

  public void setPattern(String value) {
    riskuserapiJNI.CShfeFtdcNoticePatternField_Pattern_set(swigCPtr, this, value);
  }

  public String getPattern() {
    return riskuserapiJNI.CShfeFtdcNoticePatternField_Pattern_get(swigCPtr, this);
  }

  public CShfeFtdcNoticePatternField() {
    this(riskuserapiJNI.new_CShfeFtdcNoticePatternField(), true);
  }

}
