/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcPositionStatField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcPositionStatField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcPositionStatField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcPositionStatField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_BrokerID_get(swigCPtr, this);
  }

  public void setExchangeProductInstID(String value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_ExchangeProductInstID_set(swigCPtr, this, value);
  }

  public String getExchangeProductInstID() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_ExchangeProductInstID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_InvestorID_get(swigCPtr, this);
  }

  public void setYdPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_YdPosition_set(swigCPtr, this, value);
  }

  public int getYdPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_YdPosition_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_Position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_Position_get(swigCPtr, this);
  }

  public void setLongPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_LongPosition_set(swigCPtr, this, value);
  }

  public int getLongPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_LongPosition_get(swigCPtr, this);
  }

  public void setShortPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_ShortPosition_set(swigCPtr, this, value);
  }

  public int getShortPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_ShortPosition_get(swigCPtr, this);
  }

  public void setNetPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_NetPosition_set(swigCPtr, this, value);
  }

  public int getNetPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_NetPosition_get(swigCPtr, this);
  }

  public void setSpecuLongPosi(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_SpecuLongPosi_set(swigCPtr, this, value);
  }

  public int getSpecuLongPosi() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_SpecuLongPosi_get(swigCPtr, this);
  }

  public void setSpecuShortPosi(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_SpecuShortPosi_set(swigCPtr, this, value);
  }

  public int getSpecuShortPosi() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_SpecuShortPosi_get(swigCPtr, this);
  }

  public void setHedgeLongPosi(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_HedgeLongPosi_set(swigCPtr, this, value);
  }

  public int getHedgeLongPosi() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_HedgeLongPosi_get(swigCPtr, this);
  }

  public void setHedgeShortPosi(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_HedgeShortPosi_set(swigCPtr, this, value);
  }

  public int getHedgeShortPosi() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_HedgeShortPosi_get(swigCPtr, this);
  }

  public void setTodayPosition(int value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_TodayPosition_set(swigCPtr, this, value);
  }

  public int getTodayPosition() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_TodayPosition_get(swigCPtr, this);
  }

  public void setPositionCost(double value) {
    riskuserapiJNI.CShfeFtdcPositionStatField_PositionCost_set(swigCPtr, this, value);
  }

  public double getPositionCost() {
    return riskuserapiJNI.CShfeFtdcPositionStatField_PositionCost_get(swigCPtr, this);
  }

  public CShfeFtdcPositionStatField() {
    this(riskuserapiJNI.new_CShfeFtdcPositionStatField(), true);
  }

}
