/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskNotifyPatternField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskNotifyPatternField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskNotifyPatternField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskNotifyPatternField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_UserID_get(swigCPtr, this);
  }

  public void setNotifyClass(char value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_NotifyClass_set(swigCPtr, this, value);
  }

  public char getNotifyClass() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_NotifyClass_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsActive_get(swigCPtr, this);
  }

  public void setIsAutoSystem(int value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoSystem_set(swigCPtr, this, value);
  }

  public int getIsAutoSystem() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoSystem_get(swigCPtr, this);
  }

  public void setIsAutoSMS(int value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoSMS_set(swigCPtr, this, value);
  }

  public int getIsAutoSMS() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoSMS_get(swigCPtr, this);
  }

  public void setIsAutoEmail(int value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoEmail_set(swigCPtr, this, value);
  }

  public int getIsAutoEmail() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_IsAutoEmail_get(swigCPtr, this);
  }

  public void setSystemPattern(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_SystemPattern_set(swigCPtr, this, value);
  }

  public String getSystemPattern() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_SystemPattern_get(swigCPtr, this);
  }

  public void setSMSPattern(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_SMSPattern_set(swigCPtr, this, value);
  }

  public String getSMSPattern() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_SMSPattern_get(swigCPtr, this);
  }

  public void setEmailPattern(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_EmailPattern_set(swigCPtr, this, value);
  }

  public String getEmailPattern() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_EmailPattern_get(swigCPtr, this);
  }

  public void setReserve(String value) {
    riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_Reserve_set(swigCPtr, this, value);
  }

  public String getReserve() {
    return riskuserapiJNI.CShfeFtdcRiskNotifyPatternField_Reserve_get(swigCPtr, this);
  }

  public CShfeFtdcRiskNotifyPatternField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskNotifyPatternField(), true);
  }

}
