/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcMarketDataBaseField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcMarketDataBaseField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcMarketDataBaseField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcMarketDataBaseField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcMarketDataBaseField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcMarketDataBaseField_TradingDay_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setPreClosePrice(double value) {
    riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreClosePrice_set(swigCPtr, this, value);
  }

  public double getPreClosePrice() {
    return riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreClosePrice_get(swigCPtr, this);
  }

  public void setPreOpenInterest(double value) {
    riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreOpenInterest_set(swigCPtr, this, value);
  }

  public double getPreOpenInterest() {
    return riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreOpenInterest_get(swigCPtr, this);
  }

  public void setPreDelta(double value) {
    riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreDelta_set(swigCPtr, this, value);
  }

  public double getPreDelta() {
    return riskuserapiJNI.CShfeFtdcMarketDataBaseField_PreDelta_get(swigCPtr, this);
  }

  public CShfeFtdcMarketDataBaseField() {
    this(riskuserapiJNI.new_CShfeFtdcMarketDataBaseField(), true);
  }

}
