/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSetSmsStatusField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSetSmsStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSetSmsStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSetSmsStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_SequenceNo_get(swigCPtr, this);
  }

  public void setType(char value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_Type_set(swigCPtr, this, value);
  }

  public char getType() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_Type_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_UserID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_InvestorID_get(swigCPtr, this);
  }

  public void setStatus(char value) {
    riskuserapiJNI.CShfeFtdcSetSmsStatusField_Status_set(swigCPtr, this, value);
  }

  public char getStatus() {
    return riskuserapiJNI.CShfeFtdcSetSmsStatusField_Status_get(swigCPtr, this);
  }

  public CShfeFtdcSetSmsStatusField() {
    this(riskuserapiJNI.new_CShfeFtdcSetSmsStatusField(), true);
  }

}
