/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcContractBankField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcContractBankField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcContractBankField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcContractBankField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcContractBankField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcContractBankField_BrokerID_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    riskuserapiJNI.CShfeFtdcContractBankField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return riskuserapiJNI.CShfeFtdcContractBankField_BankID_get(swigCPtr, this);
  }

  public void setBankBrchID(String value) {
    riskuserapiJNI.CShfeFtdcContractBankField_BankBrchID_set(swigCPtr, this, value);
  }

  public String getBankBrchID() {
    return riskuserapiJNI.CShfeFtdcContractBankField_BankBrchID_get(swigCPtr, this);
  }

  public void setBankName(String value) {
    riskuserapiJNI.CShfeFtdcContractBankField_BankName_set(swigCPtr, this, value);
  }

  public String getBankName() {
    return riskuserapiJNI.CShfeFtdcContractBankField_BankName_get(swigCPtr, this);
  }

  public CShfeFtdcContractBankField() {
    this(riskuserapiJNI.new_CShfeFtdcContractBankField(), true);
  }

}
