/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcLinkManField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcLinkManField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcLinkManField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcLinkManField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcLinkManField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcLinkManField_InvestorID_get(swigCPtr, this);
  }

  public void setPersonType(char value) {
    riskuserapiJNI.CShfeFtdcLinkManField_PersonType_set(swigCPtr, this, value);
  }

  public char getPersonType() {
    return riskuserapiJNI.CShfeFtdcLinkManField_PersonType_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    riskuserapiJNI.CShfeFtdcLinkManField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return riskuserapiJNI.CShfeFtdcLinkManField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return riskuserapiJNI.CShfeFtdcLinkManField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setPersonName(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_PersonName_set(swigCPtr, this, value);
  }

  public String getPersonName() {
    return riskuserapiJNI.CShfeFtdcLinkManField_PersonName_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return riskuserapiJNI.CShfeFtdcLinkManField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return riskuserapiJNI.CShfeFtdcLinkManField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return riskuserapiJNI.CShfeFtdcLinkManField_ZipCode_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    riskuserapiJNI.CShfeFtdcLinkManField_Priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return riskuserapiJNI.CShfeFtdcLinkManField_Priority_get(swigCPtr, this);
  }

  public void setUOAZipCode(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_UOAZipCode_set(swigCPtr, this, value);
  }

  public String getUOAZipCode() {
    return riskuserapiJNI.CShfeFtdcLinkManField_UOAZipCode_get(swigCPtr, this);
  }

  public void setPersonFullName(String value) {
    riskuserapiJNI.CShfeFtdcLinkManField_PersonFullName_set(swigCPtr, this, value);
  }

  public String getPersonFullName() {
    return riskuserapiJNI.CShfeFtdcLinkManField_PersonFullName_get(swigCPtr, this);
  }

  public CShfeFtdcLinkManField() {
    this(riskuserapiJNI.new_CShfeFtdcLinkManField(), true);
  }

}
