/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcForceClosePositionRuleField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcForceClosePositionRuleField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcForceClosePositionRuleField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcForceClosePositionRuleField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_ProductInstrumentID_set(swigCPtr, this, value);
  }

  public String getProductInstrumentID() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_ProductInstrumentID_get(swigCPtr, this);
  }

  public void setFCPosiDirection(char value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCPosiDirection_set(swigCPtr, this, value);
  }

  public char getFCPosiDirection() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCPosiDirection_get(swigCPtr, this);
  }

  public void setFCHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCHedgeFlag_set(swigCPtr, this, value);
  }

  public char getFCHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCHedgeFlag_get(swigCPtr, this);
  }

  public void setFCCombPosiFlag(char value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCCombPosiFlag_set(swigCPtr, this, value);
  }

  public char getFCCombPosiFlag() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCCombPosiFlag_get(swigCPtr, this);
  }

  public void setFCHistoryPosiOrder(char value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCHistoryPosiOrder_set(swigCPtr, this, value);
  }

  public char getFCHistoryPosiOrder() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCHistoryPosiOrder_get(swigCPtr, this);
  }

  public void setFCPrice(char value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCPrice_set(swigCPtr, this, value);
  }

  public char getFCPrice() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCPrice_get(swigCPtr, this);
  }

  public void setPriceTick(int value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_PriceTick_set(swigCPtr, this, value);
  }

  public int getPriceTick() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_PriceTick_get(swigCPtr, this);
  }

  public void setFCRulePriority(String value) {
    riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCRulePriority_set(swigCPtr, this, value);
  }

  public String getFCRulePriority() {
    return riskuserapiJNI.CShfeFtdcForceClosePositionRuleField_FCRulePriority_get(swigCPtr, this);
  }

  public CShfeFtdcForceClosePositionRuleField() {
    this(riskuserapiJNI.new_CShfeFtdcForceClosePositionRuleField(), true);
  }

}
