/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskSyncInvestorField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskSyncInvestorField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskSyncInvestorField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskSyncInvestorField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAction(char value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Action_set(swigCPtr, this, value);
  }

  public char getAction() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Action_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorGroupID(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorGroupID_set(swigCPtr, this, value);
  }

  public String getInvestorGroupID() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorGroupID_get(swigCPtr, this);
  }

  public void setInvestorName(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorName_set(swigCPtr, this, value);
  }

  public String getInvestorName() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_InvestorName_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_IsActive_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Address_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_OpenDate_get(swigCPtr, this);
  }

  public void setMobile(String value) {
    riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Mobile_set(swigCPtr, this, value);
  }

  public String getMobile() {
    return riskuserapiJNI.CShfeFtdcRiskSyncInvestorField_Mobile_get(swigCPtr, this);
  }

  public CShfeFtdcRiskSyncInvestorField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskSyncInvestorField(), true);
  }

}
