/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcQryTraderField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcQryTraderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcQryTraderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcQryTraderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcQryTraderField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcQryTraderField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    riskuserapiJNI.CShfeFtdcQryTraderField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return riskuserapiJNI.CShfeFtdcQryTraderField_ParticipantID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    riskuserapiJNI.CShfeFtdcQryTraderField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return riskuserapiJNI.CShfeFtdcQryTraderField_TraderID_get(swigCPtr, this);
  }

  public CShfeFtdcQryTraderField() {
    this(riskuserapiJNI.new_CShfeFtdcQryTraderField(), true);
  }

}
