/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcIsWriteOnceField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcIsWriteOnceField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcIsWriteOnceField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcIsWriteOnceField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcIsWriteOnceField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcIsWriteOnceField_BrokerID_get(swigCPtr, this);
  }

  public void setIsWriteOnce(int value) {
    riskuserapiJNI.CShfeFtdcIsWriteOnceField_IsWriteOnce_set(swigCPtr, this, value);
  }

  public int getIsWriteOnce() {
    return riskuserapiJNI.CShfeFtdcIsWriteOnceField_IsWriteOnce_get(swigCPtr, this);
  }

  public CShfeFtdcIsWriteOnceField() {
    this(riskuserapiJNI.new_CShfeFtdcIsWriteOnceField(), true);
  }

}
