/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskNtfSequenceField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskNtfSequenceField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskNtfSequenceField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskNtfSequenceField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcRiskNtfSequenceField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcRiskNtfSequenceField_SequenceNo_get(swigCPtr, this);
  }

  public void setDataType(String value) {
    riskuserapiJNI.CShfeFtdcRiskNtfSequenceField_DataType_set(swigCPtr, this, value);
  }

  public String getDataType() {
    return riskuserapiJNI.CShfeFtdcRiskNtfSequenceField_DataType_get(swigCPtr, this);
  }

  public CShfeFtdcRiskNtfSequenceField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskNtfSequenceField(), true);
  }

}
