/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcInvestorTestResultField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcInvestorTestResultField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcInvestorTestResultField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcInvestorTestResultField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_InvestorID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_AccountID_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_CurrencyID_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_Balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_Balance_get(swigCPtr, this);
  }

  public void setAvailable(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_Available_set(swigCPtr, this, value);
  }

  public double getAvailable() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_Available_get(swigCPtr, this);
  }

  public void setLongExeMargin(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_LongExeMargin_set(swigCPtr, this, value);
  }

  public double getLongExeMargin() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_LongExeMargin_get(swigCPtr, this);
  }

  public void setShortExeMargin(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_ShortExeMargin_set(swigCPtr, this, value);
  }

  public double getShortExeMargin() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_ShortExeMargin_get(swigCPtr, this);
  }

  public void setExeMoney(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_ExeMoney_set(swigCPtr, this, value);
  }

  public double getExeMoney() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_ExeMoney_get(swigCPtr, this);
  }

  public void setExeProfit(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_ExeProfit_set(swigCPtr, this, value);
  }

  public double getExeProfit() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_ExeProfit_get(swigCPtr, this);
  }

  public void setReleaseMoney(double value) {
    riskuserapiJNI.CShfeFtdcInvestorTestResultField_ReleaseMoney_set(swigCPtr, this, value);
  }

  public double getReleaseMoney() {
    return riskuserapiJNI.CShfeFtdcInvestorTestResultField_ReleaseMoney_get(swigCPtr, this);
  }

  public CShfeFtdcInvestorTestResultField() {
    this(riskuserapiJNI.new_CShfeFtdcInvestorTestResultField(), true);
  }

}
