/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRspInvestorTradeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRspInvestorTradeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRspInvestorTradeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRspInvestorTradeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_InstrumentID_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_UserID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ExchangeID_get(swigCPtr, this);
  }

  public void setTradeID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeID_set(swigCPtr, this, value);
  }

  public String getTradeID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeID_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Direction_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderSysID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ClientID_get(swigCPtr, this);
  }

  public void setTradingRole(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradingRole_set(swigCPtr, this, value);
  }

  public char getTradingRole() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradingRole_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setOffsetFlag(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OffsetFlag_set(swigCPtr, this, value);
  }

  public char getOffsetFlag() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OffsetFlag_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Price_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_Volume_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeTime_get(swigCPtr, this);
  }

  public void setTradeType(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeType_set(swigCPtr, this, value);
  }

  public char getTradeType() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeType_get(swigCPtr, this);
  }

  public void setPriceSource(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_PriceSource_set(swigCPtr, this, value);
  }

  public char getPriceSource() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_PriceSource_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TraderID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_OrderLocalID_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_ClearingPartID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BusinessUnit_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_SequenceNo_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_SettlementID_get(swigCPtr, this);
  }

  public void setBrokerOrderSeq(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BrokerOrderSeq_set(swigCPtr, this, value);
  }

  public int getBrokerOrderSeq() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_BrokerOrderSeq_get(swigCPtr, this);
  }

  public void setTradeSource(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeSource_set(swigCPtr, this, value);
  }

  public char getTradeSource() {
    return riskuserapiJNI.CShfeFtdcRspInvestorTradeField_TradeSource_get(swigCPtr, this);
  }

  public CShfeFtdcRspInvestorTradeField() {
    this(riskuserapiJNI.new_CShfeFtdcRspInvestorTradeField(), true);
  }

}
