/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcInstrumentField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcInstrumentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcInstrumentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcInstrumentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ExchangeID_get(swigCPtr, this);
  }

  public void setInstrumentName(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_InstrumentName_set(swigCPtr, this, value);
  }

  public String getInstrumentName() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_InstrumentName_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ProductID_get(swigCPtr, this);
  }

  public void setProductClass(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ProductClass_set(swigCPtr, this, value);
  }

  public char getProductClass() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ProductClass_get(swigCPtr, this);
  }

  public void setDeliveryYear(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_DeliveryYear_set(swigCPtr, this, value);
  }

  public int getDeliveryYear() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_DeliveryYear_get(swigCPtr, this);
  }

  public void setDeliveryMonth(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_DeliveryMonth_set(swigCPtr, this, value);
  }

  public int getDeliveryMonth() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_DeliveryMonth_get(swigCPtr, this);
  }

  public void setMaxMarketOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_MaxMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxMarketOrderVolume() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_MaxMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMinMarketOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_MinMarketOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinMarketOrderVolume() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_MinMarketOrderVolume_get(swigCPtr, this);
  }

  public void setMaxLimitOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_MaxLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMaxLimitOrderVolume() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_MaxLimitOrderVolume_get(swigCPtr, this);
  }

  public void setMinLimitOrderVolume(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_MinLimitOrderVolume_set(swigCPtr, this, value);
  }

  public int getMinLimitOrderVolume() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_MinLimitOrderVolume_get(swigCPtr, this);
  }

  public void setVolumeMultiple(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_VolumeMultiple_set(swigCPtr, this, value);
  }

  public int getVolumeMultiple() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_VolumeMultiple_get(swigCPtr, this);
  }

  public void setPriceTick(double value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_PriceTick_set(swigCPtr, this, value);
  }

  public double getPriceTick() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_PriceTick_get(swigCPtr, this);
  }

  public void setCreateDate(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_CreateDate_set(swigCPtr, this, value);
  }

  public String getCreateDate() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_CreateDate_get(swigCPtr, this);
  }

  public void setOpenDate(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_OpenDate_set(swigCPtr, this, value);
  }

  public String getOpenDate() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_OpenDate_get(swigCPtr, this);
  }

  public void setExpireDate(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ExpireDate_set(swigCPtr, this, value);
  }

  public String getExpireDate() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ExpireDate_get(swigCPtr, this);
  }

  public void setStartDelivDate(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_StartDelivDate_set(swigCPtr, this, value);
  }

  public String getStartDelivDate() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_StartDelivDate_get(swigCPtr, this);
  }

  public void setEndDelivDate(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_EndDelivDate_set(swigCPtr, this, value);
  }

  public String getEndDelivDate() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_EndDelivDate_get(swigCPtr, this);
  }

  public void setInstLifePhase(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_InstLifePhase_set(swigCPtr, this, value);
  }

  public char getInstLifePhase() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_InstLifePhase_get(swigCPtr, this);
  }

  public void setIsTrading(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_IsTrading_set(swigCPtr, this, value);
  }

  public int getIsTrading() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_IsTrading_get(swigCPtr, this);
  }

  public void setPositionType(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_PositionType_set(swigCPtr, this, value);
  }

  public char getPositionType() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_PositionType_get(swigCPtr, this);
  }

  public void setPositionDateType(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_PositionDateType_set(swigCPtr, this, value);
  }

  public char getPositionDateType() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_PositionDateType_get(swigCPtr, this);
  }

  public void setLongMarginRatio(double value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_LongMarginRatio_set(swigCPtr, this, value);
  }

  public double getLongMarginRatio() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_LongMarginRatio_get(swigCPtr, this);
  }

  public void setShortMarginRatio(double value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ShortMarginRatio_set(swigCPtr, this, value);
  }

  public double getShortMarginRatio() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ShortMarginRatio_get(swigCPtr, this);
  }

  public void setMaxMarginSideAlgorithm(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_MaxMarginSideAlgorithm_set(swigCPtr, this, value);
  }

  public char getMaxMarginSideAlgorithm() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_MaxMarginSideAlgorithm_get(swigCPtr, this);
  }

  public void setUnderlyingInstrID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_UnderlyingInstrID_set(swigCPtr, this, value);
  }

  public String getUnderlyingInstrID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_UnderlyingInstrID_get(swigCPtr, this);
  }

  public void setStrikePrice(double value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_StrikePrice_set(swigCPtr, this, value);
  }

  public double getStrikePrice() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_StrikePrice_get(swigCPtr, this);
  }

  public void setOptionsType(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_OptionsType_set(swigCPtr, this, value);
  }

  public char getOptionsType() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_OptionsType_get(swigCPtr, this);
  }

  public void setUnderlyingMultiple(double value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_UnderlyingMultiple_set(swigCPtr, this, value);
  }

  public double getUnderlyingMultiple() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_UnderlyingMultiple_get(swigCPtr, this);
  }

  public void setCombinationType(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_CombinationType_set(swigCPtr, this, value);
  }

  public char getCombinationType() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_CombinationType_get(swigCPtr, this);
  }

  public void setProductGroupID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentField_ProductGroupID_set(swigCPtr, this, value);
  }

  public String getProductGroupID() {
    return riskuserapiJNI.CShfeFtdcInstrumentField_ProductGroupID_get(swigCPtr, this);
  }

  public CShfeFtdcInstrumentField() {
    this(riskuserapiJNI.new_CShfeFtdcInstrumentField(), true);
  }

}
