/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcInstrumentStatusField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcInstrumentStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcInstrumentStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcInstrumentStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_ExchangeID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setSettlementGroupID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_SettlementGroupID_set(swigCPtr, this, value);
  }

  public String getSettlementGroupID() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_SettlementGroupID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_InstrumentID_get(swigCPtr, this);
  }

  public void setInstrumentStatus(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_InstrumentStatus_set(swigCPtr, this, value);
  }

  public char getInstrumentStatus() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_InstrumentStatus_get(swigCPtr, this);
  }

  public void setTradingSegmentSN(int value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_TradingSegmentSN_set(swigCPtr, this, value);
  }

  public int getTradingSegmentSN() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_TradingSegmentSN_get(swigCPtr, this);
  }

  public void setEnterTime(String value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_EnterTime_set(swigCPtr, this, value);
  }

  public String getEnterTime() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_EnterTime_get(swigCPtr, this);
  }

  public void setEnterReason(char value) {
    riskuserapiJNI.CShfeFtdcInstrumentStatusField_EnterReason_set(swigCPtr, this, value);
  }

  public char getEnterReason() {
    return riskuserapiJNI.CShfeFtdcInstrumentStatusField_EnterReason_get(swigCPtr, this);
  }

  public CShfeFtdcInstrumentStatusField() {
    this(riskuserapiJNI.new_CShfeFtdcInstrumentStatusField(), true);
  }

}
