/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcErrOrderActionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcErrOrderActionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcErrOrderActionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcErrOrderActionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_InvestorID_get(swigCPtr, this);
  }

  public void setOrderActionRef(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderActionRef_set(swigCPtr, this, value);
  }

  public int getOrderActionRef() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderActionRef_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderRef_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_RequestID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_SessionID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ExchangeID_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderSysID_get(swigCPtr, this);
  }

  public void setActionFlag(char value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionFlag_set(swigCPtr, this, value);
  }

  public char getActionFlag() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionFlag_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_LimitPrice_get(swigCPtr, this);
  }

  public void setVolumeChange(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_VolumeChange_set(swigCPtr, this, value);
  }

  public int getVolumeChange() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_VolumeChange_get(swigCPtr, this);
  }

  public void setActionDate(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionDate_set(swigCPtr, this, value);
  }

  public String getActionDate() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionDate_get(swigCPtr, this);
  }

  public void setActionTime(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionTime_set(swigCPtr, this, value);
  }

  public String getActionTime() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionTime_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_InstallID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderLocalID_get(swigCPtr, this);
  }

  public void setActionLocalID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionLocalID_set(swigCPtr, this, value);
  }

  public String getActionLocalID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ActionLocalID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ClientID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_BusinessUnit_get(swigCPtr, this);
  }

  public void setOrderActionStatus(char value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderActionStatus_set(swigCPtr, this, value);
  }

  public char getOrderActionStatus() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_OrderActionStatus_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_UserID_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_StatusMsg_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_InstrumentID_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_BranchID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_MacAddress_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    riskuserapiJNI.CShfeFtdcErrOrderActionField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return riskuserapiJNI.CShfeFtdcErrOrderActionField_ErrorMsg_get(swigCPtr, this);
  }

  public CShfeFtdcErrOrderActionField() {
    this(riskuserapiJNI.new_CShfeFtdcErrOrderActionField(), true);
  }

}
