/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcFrontStatusField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcFrontStatusField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcFrontStatusField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcFrontStatusField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrontID(int value) {
    riskuserapiJNI.CShfeFtdcFrontStatusField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return riskuserapiJNI.CShfeFtdcFrontStatusField_FrontID_get(swigCPtr, this);
  }

  public void setLastReportDate(String value) {
    riskuserapiJNI.CShfeFtdcFrontStatusField_LastReportDate_set(swigCPtr, this, value);
  }

  public String getLastReportDate() {
    return riskuserapiJNI.CShfeFtdcFrontStatusField_LastReportDate_get(swigCPtr, this);
  }

  public void setLastReportTime(String value) {
    riskuserapiJNI.CShfeFtdcFrontStatusField_LastReportTime_set(swigCPtr, this, value);
  }

  public String getLastReportTime() {
    return riskuserapiJNI.CShfeFtdcFrontStatusField_LastReportTime_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    riskuserapiJNI.CShfeFtdcFrontStatusField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return riskuserapiJNI.CShfeFtdcFrontStatusField_IsActive_get(swigCPtr, this);
  }

  public CShfeFtdcFrontStatusField() {
    this(riskuserapiJNI.new_CShfeFtdcFrontStatusField(), true);
  }

}
