/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSeqTradingCodeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSeqTradingCodeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSeqTradingCodeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSeqTradingCodeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUniqSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_UniqSequenceNo_set(swigCPtr, this, value);
  }

  public int getUniqSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_UniqSequenceNo_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_InvestorID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_BrokerID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ExchangeID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ClientID_get(swigCPtr, this);
  }

  public void setIsActive(int value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_IsActive_set(swigCPtr, this, value);
  }

  public int getIsActive() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_IsActive_get(swigCPtr, this);
  }

  public void setAction(char value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_Action_set(swigCPtr, this, value);
  }

  public char getAction() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_Action_get(swigCPtr, this);
  }

  public void setClientIDType(char value) {
    riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ClientIDType_set(swigCPtr, this, value);
  }

  public char getClientIDType() {
    return riskuserapiJNI.CShfeFtdcSeqTradingCodeField_ClientIDType_get(swigCPtr, this);
  }

  public CShfeFtdcSeqTradingCodeField() {
    this(riskuserapiJNI.new_CShfeFtdcSeqTradingCodeField(), true);
  }

}
