/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSyncingInvestorPositionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSyncingInvestorPositionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSyncingInvestorPositionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSyncingInvestorPositionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InstrumentID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InvestorID_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PosiDirection_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPositionDate(char value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionDate_set(swigCPtr, this, value);
  }

  public char getPositionDate() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionDate_get(swigCPtr, this);
  }

  public void setYdPosition(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_YdPosition_set(swigCPtr, this, value);
  }

  public int getYdPosition() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_YdPosition_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_Position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_Position_get(swigCPtr, this);
  }

  public void setLongFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_LongFrozen_set(swigCPtr, this, value);
  }

  public int getLongFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_LongFrozen_get(swigCPtr, this);
  }

  public void setShortFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ShortFrozen_set(swigCPtr, this, value);
  }

  public int getShortFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ShortFrozen_get(swigCPtr, this);
  }

  public void setLongFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_LongFrozenAmount_set(swigCPtr, this, value);
  }

  public double getLongFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_LongFrozenAmount_get(swigCPtr, this);
  }

  public void setShortFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ShortFrozenAmount_set(swigCPtr, this, value);
  }

  public double getShortFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ShortFrozenAmount_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenVolume_get(swigCPtr, this);
  }

  public void setCloseVolume(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseVolume_set(swigCPtr, this, value);
  }

  public int getCloseVolume() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseVolume_get(swigCPtr, this);
  }

  public void setOpenAmount(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenAmount_set(swigCPtr, this, value);
  }

  public double getOpenAmount() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenAmount_get(swigCPtr, this);
  }

  public void setCloseAmount(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseAmount_set(swigCPtr, this, value);
  }

  public double getCloseAmount() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseAmount_get(swigCPtr, this);
  }

  public void setPositionCost(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionCost_set(swigCPtr, this, value);
  }

  public double getPositionCost() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionCost_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PreMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_UseMargin_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenMargin_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenCash_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CashIn_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_Commission_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfit_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PositionProfit_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_SettlementPrice_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_SettlementID_get(swigCPtr, this);
  }

  public void setOpenCost(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenCost_set(swigCPtr, this, value);
  }

  public double getOpenCost() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OpenCost_get(swigCPtr, this);
  }

  public void setExchangeMargin(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ExchangeMargin_set(swigCPtr, this, value);
  }

  public double getExchangeMargin() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ExchangeMargin_get(swigCPtr, this);
  }

  public void setCombPosition(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombPosition_set(swigCPtr, this, value);
  }

  public int getCombPosition() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombPosition_get(swigCPtr, this);
  }

  public void setCombLongFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombLongFrozen_set(swigCPtr, this, value);
  }

  public int getCombLongFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombLongFrozen_get(swigCPtr, this);
  }

  public void setCombShortFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombShortFrozen_set(swigCPtr, this, value);
  }

  public int getCombShortFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CombShortFrozen_get(swigCPtr, this);
  }

  public void setCloseProfitByDate(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfitByDate_set(swigCPtr, this, value);
  }

  public double getCloseProfitByDate() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfitByDate_get(swigCPtr, this);
  }

  public void setCloseProfitByTrade(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfitByTrade_set(swigCPtr, this, value);
  }

  public double getCloseProfitByTrade() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_CloseProfitByTrade_get(swigCPtr, this);
  }

  public void setTodayPosition(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_TodayPosition_set(swigCPtr, this, value);
  }

  public int getTodayPosition() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_TodayPosition_get(swigCPtr, this);
  }

  public void setMarginRateByMoney(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_MarginRateByMoney_set(swigCPtr, this, value);
  }

  public double getMarginRateByMoney() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_MarginRateByMoney_get(swigCPtr, this);
  }

  public void setMarginRateByVolume(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_MarginRateByVolume_set(swigCPtr, this, value);
  }

  public double getMarginRateByVolume() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_MarginRateByVolume_get(swigCPtr, this);
  }

  public void setStrikeFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_StrikeFrozen_set(swigCPtr, this, value);
  }

  public int getStrikeFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_StrikeFrozen_get(swigCPtr, this);
  }

  public void setStrikeFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_StrikeFrozenAmount_set(swigCPtr, this, value);
  }

  public double getStrikeFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_StrikeFrozenAmount_get(swigCPtr, this);
  }

  public void setAbandonFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_AbandonFrozen_set(swigCPtr, this, value);
  }

  public int getAbandonFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_AbandonFrozen_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_ExchangeID_get(swigCPtr, this);
  }

  public void setYdStrikeFrozen(int value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_YdStrikeFrozen_set(swigCPtr, this, value);
  }

  public int getYdStrikeFrozen() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_YdStrikeFrozen_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setOptionValue(double value) {
    riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OptionValue_set(swigCPtr, this, value);
  }

  public double getOptionValue() {
    return riskuserapiJNI.CShfeFtdcSyncingInvestorPositionField_OptionValue_get(swigCPtr, this);
  }

  public CShfeFtdcSyncingInvestorPositionField() {
    this(riskuserapiJNI.new_CShfeFtdcSyncingInvestorPositionField(), true);
  }

}
