/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSTSettlePriceField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSTSettlePriceField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSTSettlePriceField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSTSettlePriceField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDay(int value) {
    riskuserapiJNI.CShfeFtdcSTSettlePriceField_Day_set(swigCPtr, this, value);
  }

  public int getDay() {
    return riskuserapiJNI.CShfeFtdcSTSettlePriceField_Day_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcSTSettlePriceField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcSTSettlePriceField_InstrumentID_get(swigCPtr, this);
  }

  public void setPriceType(char value) {
    riskuserapiJNI.CShfeFtdcSTSettlePriceField_PriceType_set(swigCPtr, this, value);
  }

  public char getPriceType() {
    return riskuserapiJNI.CShfeFtdcSTSettlePriceField_PriceType_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    riskuserapiJNI.CShfeFtdcSTSettlePriceField_Price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return riskuserapiJNI.CShfeFtdcSTSettlePriceField_Price_get(swigCPtr, this);
  }

  public CShfeFtdcSTSettlePriceField() {
    this(riskuserapiJNI.new_CShfeFtdcSTSettlePriceField(), true);
  }

}
