/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcPredictRiskPositionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcPredictRiskPositionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcPredictRiskPositionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcPredictRiskPositionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_InstrumentID_get(swigCPtr, this);
  }

  public void setLongVol(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_LongVol_set(swigCPtr, this, value);
  }

  public int getLongVol() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_LongVol_get(swigCPtr, this);
  }

  public void setShortVol(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_ShortVol_set(swigCPtr, this, value);
  }

  public int getShortVol() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_ShortVol_get(swigCPtr, this);
  }

  public void setNetVol(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_NetVol_set(swigCPtr, this, value);
  }

  public int getNetVol() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_NetVol_get(swigCPtr, this);
  }

  public void setPrice0(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Price0_set(swigCPtr, this, value);
  }

  public double getPrice0() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Price0_get(swigCPtr, this);
  }

  public void setPrice1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Price1_set(swigCPtr, this, value);
  }

  public double getPrice1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Price1_get(swigCPtr, this);
  }

  public void setLimit1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit1_set(swigCPtr, this, value);
  }

  public double getLimit1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit1_get(swigCPtr, this);
  }

  public void setLimit2(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit2_set(swigCPtr, this, value);
  }

  public double getLimit2() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit2_get(swigCPtr, this);
  }

  public void setLimit3(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit3_set(swigCPtr, this, value);
  }

  public double getLimit3() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit3_get(swigCPtr, this);
  }

  public void setLimit4(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit4_set(swigCPtr, this, value);
  }

  public double getLimit4() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Limit4_get(swigCPtr, this);
  }

  public void setMultiple(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Multiple_set(swigCPtr, this, value);
  }

  public int getMultiple() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Multiple_get(swigCPtr, this);
  }

  public void setLose1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose1_set(swigCPtr, this, value);
  }

  public double getLose1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose1_get(swigCPtr, this);
  }

  public void setLose2(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose2_set(swigCPtr, this, value);
  }

  public double getLose2() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose2_get(swigCPtr, this);
  }

  public void setLose3(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose3_set(swigCPtr, this, value);
  }

  public double getLose3() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose3_get(swigCPtr, this);
  }

  public void setLose4(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose4_set(swigCPtr, this, value);
  }

  public double getLose4() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Lose4_get(swigCPtr, this);
  }

  public void setLeftVol(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_LeftVol_set(swigCPtr, this, value);
  }

  public int getLeftVol() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_LeftVol_get(swigCPtr, this);
  }

  public void setShouldClose(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_ShouldClose_set(swigCPtr, this, value);
  }

  public int getShouldClose() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_ShouldClose_get(swigCPtr, this);
  }

  public void setCanClose(int value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_CanClose_set(swigCPtr, this, value);
  }

  public int getCanClose() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_CanClose_get(swigCPtr, this);
  }

  public void setCurrMarginRate(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_CurrMarginRate_set(swigCPtr, this, value);
  }

  public double getCurrMarginRate() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_CurrMarginRate_get(swigCPtr, this);
  }

  public void setMarginRate1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_MarginRate1_set(swigCPtr, this, value);
  }

  public double getMarginRate1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_MarginRate1_get(swigCPtr, this);
  }

  public void setNetMargin1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_NetMargin1_set(swigCPtr, this, value);
  }

  public double getNetMargin1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_NetMargin1_get(swigCPtr, this);
  }

  public void setAvailable1(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Available1_set(swigCPtr, this, value);
  }

  public double getAvailable1() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Available1_get(swigCPtr, this);
  }

  public void setMargin1PerVol(double value) {
    riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Margin1PerVol_set(swigCPtr, this, value);
  }

  public double getMargin1PerVol() {
    return riskuserapiJNI.CShfeFtdcPredictRiskPositionField_Margin1PerVol_get(swigCPtr, this);
  }

  public CShfeFtdcPredictRiskPositionField() {
    this(riskuserapiJNI.new_CShfeFtdcPredictRiskPositionField(), true);
  }

}
