/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcQrySyncDelaySwapField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcQrySyncDelaySwapField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcQrySyncDelaySwapField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcQrySyncDelaySwapField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcQrySyncDelaySwapField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcQrySyncDelaySwapField_BrokerID_get(swigCPtr, this);
  }

  public void setDelaySwapSeqNo(String value) {
    riskuserapiJNI.CShfeFtdcQrySyncDelaySwapField_DelaySwapSeqNo_set(swigCPtr, this, value);
  }

  public String getDelaySwapSeqNo() {
    return riskuserapiJNI.CShfeFtdcQrySyncDelaySwapField_DelaySwapSeqNo_get(swigCPtr, this);
  }

  public CShfeFtdcQrySyncDelaySwapField() {
    this(riskuserapiJNI.new_CShfeFtdcQrySyncDelaySwapField(), true);
  }

}
