/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcDepartmentField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcDepartmentField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcDepartmentField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcDepartmentField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcDepartmentField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcDepartmentField_BrokerID_get(swigCPtr, this);
  }

  public void setDepartmentID(String value) {
    riskuserapiJNI.CShfeFtdcDepartmentField_DepartmentID_set(swigCPtr, this, value);
  }

  public String getDepartmentID() {
    return riskuserapiJNI.CShfeFtdcDepartmentField_DepartmentID_get(swigCPtr, this);
  }

  public void setDepartmentName(String value) {
    riskuserapiJNI.CShfeFtdcDepartmentField_DepartmentName_set(swigCPtr, this, value);
  }

  public String getDepartmentName() {
    return riskuserapiJNI.CShfeFtdcDepartmentField_DepartmentName_get(swigCPtr, this);
  }

  public CShfeFtdcDepartmentField() {
    this(riskuserapiJNI.new_CShfeFtdcDepartmentField(), true);
  }

}
