/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskLoginInfoField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskLoginInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskLoginInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskLoginInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRiskLoginInfoField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRiskLoginInfoField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcRiskLoginInfoField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcRiskLoginInfoField_UserID_get(swigCPtr, this);
  }

  public void setLocalSessionID(int value) {
    riskuserapiJNI.CShfeFtdcRiskLoginInfoField_LocalSessionID_set(swigCPtr, this, value);
  }

  public int getLocalSessionID() {
    return riskuserapiJNI.CShfeFtdcRiskLoginInfoField_LocalSessionID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    riskuserapiJNI.CShfeFtdcRiskLoginInfoField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return riskuserapiJNI.CShfeFtdcRiskLoginInfoField_SessionID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    riskuserapiJNI.CShfeFtdcRiskLoginInfoField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return riskuserapiJNI.CShfeFtdcRiskLoginInfoField_FrontID_get(swigCPtr, this);
  }

  public CShfeFtdcRiskLoginInfoField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskLoginInfoField(), true);
  }

}
