/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskPatternField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskPatternField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskPatternField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskPatternField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRiskPatternField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRiskPatternField_BrokerID_get(swigCPtr, this);
  }

  public void setBizType(String value) {
    riskuserapiJNI.CShfeFtdcRiskPatternField_BizType_set(swigCPtr, this, value);
  }

  public String getBizType() {
    return riskuserapiJNI.CShfeFtdcRiskPatternField_BizType_get(swigCPtr, this);
  }

  public void setPatternID(int value) {
    riskuserapiJNI.CShfeFtdcRiskPatternField_PatternID_set(swigCPtr, this, value);
  }

  public int getPatternID() {
    return riskuserapiJNI.CShfeFtdcRiskPatternField_PatternID_get(swigCPtr, this);
  }

  public void setPatternName(String value) {
    riskuserapiJNI.CShfeFtdcRiskPatternField_PatternName_set(swigCPtr, this, value);
  }

  public String getPatternName() {
    return riskuserapiJNI.CShfeFtdcRiskPatternField_PatternName_get(swigCPtr, this);
  }

  public void setPattern(String value) {
    riskuserapiJNI.CShfeFtdcRiskPatternField_Pattern_set(swigCPtr, this, value);
  }

  public String getPattern() {
    return riskuserapiJNI.CShfeFtdcRiskPatternField_Pattern_get(swigCPtr, this);
  }

  public CShfeFtdcRiskPatternField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskPatternField(), true);
  }

}
