/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcETDCESPInsGroupParamField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcETDCESPInsGroupParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcETDCESPInsGroupParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcETDCESPInsGroupParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProductID(String value) {
    riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_ProductID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_InstrumentID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcETDCESPInsGroupParamField_SequenceNo_get(swigCPtr, this);
  }

  public CShfeFtdcETDCESPInsGroupParamField() {
    this(riskuserapiJNI.new_CShfeFtdcETDCESPInsGroupParamField(), true);
  }

}
