/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSequencialTradeField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSequencialTradeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSequencialTradeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSequencialTradeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUniqSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_UniqSequenceNo_set(swigCPtr, this, value);
  }

  public int getUniqSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_UniqSequenceNo_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_InstrumentID_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_UserID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_ExchangeID_get(swigCPtr, this);
  }

  public void setTradeID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeID_set(swigCPtr, this, value);
  }

  public String getTradeID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeID_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_Direction_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderSysID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_ClientID_get(swigCPtr, this);
  }

  public void setTradingRole(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradingRole_set(swigCPtr, this, value);
  }

  public char getTradingRole() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradingRole_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setOffsetFlag(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_OffsetFlag_set(swigCPtr, this, value);
  }

  public char getOffsetFlag() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_OffsetFlag_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_Price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_Price_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_Volume_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeTime_get(swigCPtr, this);
  }

  public void setTradeType(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeType_set(swigCPtr, this, value);
  }

  public char getTradeType() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeType_get(swigCPtr, this);
  }

  public void setPriceSource(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_PriceSource_set(swigCPtr, this, value);
  }

  public char getPriceSource() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_PriceSource_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TraderID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_OrderLocalID_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_ClearingPartID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_BusinessUnit_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_SequenceNo_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_SettlementID_get(swigCPtr, this);
  }

  public void setBrokerOrderSeq(int value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_BrokerOrderSeq_set(swigCPtr, this, value);
  }

  public int getBrokerOrderSeq() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_BrokerOrderSeq_get(swigCPtr, this);
  }

  public void setTradeSource(char value) {
    riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeSource_set(swigCPtr, this, value);
  }

  public char getTradeSource() {
    return riskuserapiJNI.CShfeFtdcSequencialTradeField_TradeSource_get(swigCPtr, this);
  }

  public CShfeFtdcSequencialTradeField() {
    this(riskuserapiJNI.new_CShfeFtdcSequencialTradeField(), true);
  }

}
