/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRemoveParkedOrderActionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRemoveParkedOrderActionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRemoveParkedOrderActionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRemoveParkedOrderActionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_InvestorID_get(swigCPtr, this);
  }

  public void setParkedOrderActionID(String value) {
    riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_ParkedOrderActionID_set(swigCPtr, this, value);
  }

  public String getParkedOrderActionID() {
    return riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_ParkedOrderActionID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return riskuserapiJNI.CShfeFtdcRemoveParkedOrderActionField_InvestUnitID_get(swigCPtr, this);
  }

  public CShfeFtdcRemoveParkedOrderActionField() {
    this(riskuserapiJNI.new_CShfeFtdcRemoveParkedOrderActionField(), true);
  }

}
