/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSTStandardField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSTStandardField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSTStandardField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSTStandardField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSTDCECombMarginUsed(int value) {
    riskuserapiJNI.CShfeFtdcSTStandardField_STDCECombMarginUsed_set(swigCPtr, this, value);
  }

  public int getSTDCECombMarginUsed() {
    return riskuserapiJNI.CShfeFtdcSTStandardField_STDCECombMarginUsed_get(swigCPtr, this);
  }

  public CShfeFtdcSTStandardField() {
    this(riskuserapiJNI.new_CShfeFtdcSTStandardField(), true);
  }

}
