/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskParamInfoField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskParamInfoField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskParamInfoField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskParamInfoField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setParamID(int value) {
    riskuserapiJNI.CShfeFtdcRiskParamInfoField_ParamID_set(swigCPtr, this, value);
  }

  public int getParamID() {
    return riskuserapiJNI.CShfeFtdcRiskParamInfoField_ParamID_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    riskuserapiJNI.CShfeFtdcRiskParamInfoField_Description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return riskuserapiJNI.CShfeFtdcRiskParamInfoField_Description_get(swigCPtr, this);
  }

  public CShfeFtdcRiskParamInfoField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskParamInfoField(), true);
  }

}
