/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSeqIPGroupMarginField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSeqIPGroupMarginField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSeqIPGroupMarginField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSeqIPGroupMarginField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUniqSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_UniqSequenceNo_set(swigCPtr, this, value);
  }

  public int getUniqSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_UniqSequenceNo_get(swigCPtr, this);
  }

  public void setProductGroupID(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ProductGroupID_set(swigCPtr, this, value);
  }

  public String getProductGroupID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ProductGroupID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_InvestorID_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_SettlementID_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenMargin_get(swigCPtr, this);
  }

  public void setLongFrozenMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongFrozenMargin_set(swigCPtr, this, value);
  }

  public double getLongFrozenMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongFrozenMargin_get(swigCPtr, this);
  }

  public void setShortFrozenMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortFrozenMargin_set(swigCPtr, this, value);
  }

  public double getShortFrozenMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortFrozenMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_UseMargin_get(swigCPtr, this);
  }

  public void setLongUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongUseMargin_set(swigCPtr, this, value);
  }

  public double getLongUseMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongUseMargin_get(swigCPtr, this);
  }

  public void setShortUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortUseMargin_set(swigCPtr, this, value);
  }

  public double getShortUseMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortUseMargin_get(swigCPtr, this);
  }

  public void setExchMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchMargin_set(swigCPtr, this, value);
  }

  public double getExchMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchMargin_get(swigCPtr, this);
  }

  public void setLongExchMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongExchMargin_set(swigCPtr, this, value);
  }

  public double getLongExchMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongExchMargin_get(swigCPtr, this);
  }

  public void setShortExchMargin(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortExchMargin_set(swigCPtr, this, value);
  }

  public double getShortExchMargin() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortExchMargin_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_CloseProfit_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_Commission_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_FrozenCash_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_CashIn_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_PositionProfit_get(swigCPtr, this);
  }

  public void setOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_OffsetAmount_set(swigCPtr, this, value);
  }

  public double getOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_OffsetAmount_get(swigCPtr, this);
  }

  public void setLongOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongOffsetAmount_set(swigCPtr, this, value);
  }

  public double getLongOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongOffsetAmount_get(swigCPtr, this);
  }

  public void setShortOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortOffsetAmount_set(swigCPtr, this, value);
  }

  public double getShortOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortOffsetAmount_get(swigCPtr, this);
  }

  public void setExchOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getExchOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchOffsetAmount_get(swigCPtr, this);
  }

  public void setLongExchOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getLongExchOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_LongExchOffsetAmount_get(swigCPtr, this);
  }

  public void setShortExchOffsetAmount(double value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortExchOffsetAmount_set(swigCPtr, this, value);
  }

  public double getShortExchOffsetAmount() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ShortExchOffsetAmount_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_HedgeFlag_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_ExchangeID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return riskuserapiJNI.CShfeFtdcSeqIPGroupMarginField_InvestUnitID_get(swigCPtr, this);
  }

  public CShfeFtdcSeqIPGroupMarginField() {
    this(riskuserapiJNI.new_CShfeFtdcSeqIPGroupMarginField(), true);
  }

}
