/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcTransferFutureToBankRspField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcTransferFutureToBankRspField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcTransferFutureToBankRspField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcTransferFutureToBankRspField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRetCode(String value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_RetCode_set(swigCPtr, this, value);
  }

  public String getRetCode() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_RetCode_get(swigCPtr, this);
  }

  public void setRetInfo(String value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_RetInfo_set(swigCPtr, this, value);
  }

  public String getRetInfo() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_RetInfo_get(swigCPtr, this);
  }

  public void setFutureAccount(String value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_FutureAccount_set(swigCPtr, this, value);
  }

  public String getFutureAccount() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_FutureAccount_get(swigCPtr, this);
  }

  public void setTradeAmt(double value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_TradeAmt_set(swigCPtr, this, value);
  }

  public double getTradeAmt() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_TradeAmt_get(swigCPtr, this);
  }

  public void setCustFee(double value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_CustFee_set(swigCPtr, this, value);
  }

  public double getCustFee() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_CustFee_get(swigCPtr, this);
  }

  public void setCurrencyCode(String value) {
    riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_CurrencyCode_set(swigCPtr, this, value);
  }

  public String getCurrencyCode() {
    return riskuserapiJNI.CShfeFtdcTransferFutureToBankRspField_CurrencyCode_get(swigCPtr, this);
  }

  public CShfeFtdcTransferFutureToBankRspField() {
    this(riskuserapiJNI.new_CShfeFtdcTransferFutureToBankRspField(), true);
  }

}
