/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRspInstPositionRateField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRspInstPositionRateField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRspInstPositionRateField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRspInstPositionRateField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_BrokerID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_InstrumentID_get(swigCPtr, this);
  }

  public void setHbtotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_little_set(swigCPtr, this, value);
  }

  public int getHbtotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_little_get(swigCPtr, this);
  }

  public void setHbtotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getHbtotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_medium_get(swigCPtr, this);
  }

  public void setHbtotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_large_set(swigCPtr, this, value);
  }

  public int getHbtotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hbtotal_amt_large_get(swigCPtr, this);
  }

  public void setHstotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_little_set(swigCPtr, this, value);
  }

  public int getHstotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_little_get(swigCPtr, this);
  }

  public void setHstotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getHstotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_medium_get(swigCPtr, this);
  }

  public void setHstotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_large_set(swigCPtr, this, value);
  }

  public int getHstotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_hstotal_amt_large_get(swigCPtr, this);
  }

  public void setHtotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_little_set(swigCPtr, this, value);
  }

  public int getHtotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_little_get(swigCPtr, this);
  }

  public void setHtotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getHtotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_medium_get(swigCPtr, this);
  }

  public void setHtotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_large_set(swigCPtr, this, value);
  }

  public int getHtotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_htotal_amt_large_get(swigCPtr, this);
  }

  public void setSbtotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_little_set(swigCPtr, this, value);
  }

  public int getSbtotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_little_get(swigCPtr, this);
  }

  public void setSbtotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getSbtotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_medium_get(swigCPtr, this);
  }

  public void setSbtotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_large_set(swigCPtr, this, value);
  }

  public int getSbtotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sbtotal_amt_large_get(swigCPtr, this);
  }

  public void setSstotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_little_set(swigCPtr, this, value);
  }

  public int getSstotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_little_get(swigCPtr, this);
  }

  public void setSstotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getSstotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_medium_get(swigCPtr, this);
  }

  public void setSstotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_large_set(swigCPtr, this, value);
  }

  public int getSstotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_sstotal_amt_large_get(swigCPtr, this);
  }

  public void setStotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_little_set(swigCPtr, this, value);
  }

  public int getStotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_little_get(swigCPtr, this);
  }

  public void setStotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getStotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_medium_get(swigCPtr, this);
  }

  public void setStotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_large_set(swigCPtr, this, value);
  }

  public int getStotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_stotal_amt_large_get(swigCPtr, this);
  }

  public void setBuytotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_little_set(swigCPtr, this, value);
  }

  public int getBuytotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_little_get(swigCPtr, this);
  }

  public void setBuytotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getBuytotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_medium_get(swigCPtr, this);
  }

  public void setBuytotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_large_set(swigCPtr, this, value);
  }

  public int getBuytotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_buytotal_amt_large_get(swigCPtr, this);
  }

  public void setSelltotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_little_set(swigCPtr, this, value);
  }

  public int getSelltotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_little_get(swigCPtr, this);
  }

  public void setSelltotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_medium_set(swigCPtr, this, value);
  }

  public int getSelltotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_medium_get(swigCPtr, this);
  }

  public void setSelltotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_large_set(swigCPtr, this, value);
  }

  public int getSelltotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_selltotal_amt_large_get(swigCPtr, this);
  }

  public void setTotal_amt_little(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_little_set(swigCPtr, this, value);
  }

  public int getTotal_amt_little() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_little_get(swigCPtr, this);
  }

  public void setTotal_amt_medium(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_medium_set(swigCPtr, this, value);
  }

  public int getTotal_amt_medium() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_medium_get(swigCPtr, this);
  }

  public void setTotal_amt_large(int value) {
    riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_large_set(swigCPtr, this, value);
  }

  public int getTotal_amt_large() {
    return riskuserapiJNI.CShfeFtdcRspInstPositionRateField_total_amt_large_get(swigCPtr, this);
  }

  public CShfeFtdcRspInstPositionRateField() {
    this(riskuserapiJNI.new_CShfeFtdcRspInstPositionRateField(), true);
  }

}
