/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRiskInstrumentGreeksField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRiskInstrumentGreeksField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRiskInstrumentGreeksField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRiskInstrumentGreeksField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_ExchangeID_get(swigCPtr, this);
  }

  public void setDelta(double value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Delta_set(swigCPtr, this, value);
  }

  public double getDelta() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Delta_get(swigCPtr, this);
  }

  public void setGamma(double value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Gamma_set(swigCPtr, this, value);
  }

  public double getGamma() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Gamma_get(swigCPtr, this);
  }

  public void setVega(double value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Vega_set(swigCPtr, this, value);
  }

  public double getVega() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Vega_get(swigCPtr, this);
  }

  public void setTheta(double value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Theta_set(swigCPtr, this, value);
  }

  public double getTheta() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_Theta_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcRiskInstrumentGreeksField_SettlementPrice_get(swigCPtr, this);
  }

  public CShfeFtdcRiskInstrumentGreeksField() {
    this(riskuserapiJNI.new_CShfeFtdcRiskInstrumentGreeksField(), true);
  }

}
