/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcSTDCECombMarginParamField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcSTDCECombMarginParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcSTDCECombMarginParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcSTDCECombMarginParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSTDCECombType(char value) {
    riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_STDCECombType_set(swigCPtr, this, value);
  }

  public char getSTDCECombType() {
    return riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_STDCECombType_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_SequenceNo_get(swigCPtr, this);
  }

  public void setProductID(String value) {
    riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_ProductID_set(swigCPtr, this, value);
  }

  public String getProductID() {
    return riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_ProductID_get(swigCPtr, this);
  }

  public void setProductID2(String value) {
    riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_ProductID2_set(swigCPtr, this, value);
  }

  public String getProductID2() {
    return riskuserapiJNI.CShfeFtdcSTDCECombMarginParamField_ProductID2_get(swigCPtr, this);
  }

  public CShfeFtdcSTDCECombMarginParamField() {
    this(riskuserapiJNI.new_CShfeFtdcSTDCECombMarginParamField(), true);
  }

}
