/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcQryRiskNotifyPatternField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcQryRiskNotifyPatternField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcQryRiskNotifyPatternField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcQryRiskNotifyPatternField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_BrokerID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_UserID_get(swigCPtr, this);
  }

  public void setReserve(String value) {
    riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_Reserve_set(swigCPtr, this, value);
  }

  public String getReserve() {
    return riskuserapiJNI.CShfeFtdcQryRiskNotifyPatternField_Reserve_get(swigCPtr, this);
  }

  public CShfeFtdcQryRiskNotifyPatternField() {
    this(riskuserapiJNI.new_CShfeFtdcQryRiskNotifyPatternField(), true);
  }

}
