/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcRspInvestorPositionField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcRspInvestorPositionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcRspInvestorPositionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcRspInvestorPositionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InstrumentID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InvestorID_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PosiDirection_get(swigCPtr, this);
  }

  public void setHedgeFlag(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_HedgeFlag_set(swigCPtr, this, value);
  }

  public char getHedgeFlag() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_HedgeFlag_get(swigCPtr, this);
  }

  public void setPositionDate(char value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionDate_set(swigCPtr, this, value);
  }

  public char getPositionDate() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionDate_get(swigCPtr, this);
  }

  public void setYdPosition(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_YdPosition_set(swigCPtr, this, value);
  }

  public int getYdPosition() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_YdPosition_get(swigCPtr, this);
  }

  public void setPosition(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_Position_set(swigCPtr, this, value);
  }

  public int getPosition() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_Position_get(swigCPtr, this);
  }

  public void setLongFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_LongFrozen_set(swigCPtr, this, value);
  }

  public int getLongFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_LongFrozen_get(swigCPtr, this);
  }

  public void setShortFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ShortFrozen_set(swigCPtr, this, value);
  }

  public int getShortFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ShortFrozen_get(swigCPtr, this);
  }

  public void setLongFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_LongFrozenAmount_set(swigCPtr, this, value);
  }

  public double getLongFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_LongFrozenAmount_get(swigCPtr, this);
  }

  public void setShortFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ShortFrozenAmount_set(swigCPtr, this, value);
  }

  public double getShortFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ShortFrozenAmount_get(swigCPtr, this);
  }

  public void setOpenVolume(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenVolume_set(swigCPtr, this, value);
  }

  public int getOpenVolume() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenVolume_get(swigCPtr, this);
  }

  public void setCloseVolume(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseVolume_set(swigCPtr, this, value);
  }

  public int getCloseVolume() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseVolume_get(swigCPtr, this);
  }

  public void setOpenAmount(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenAmount_set(swigCPtr, this, value);
  }

  public double getOpenAmount() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenAmount_get(swigCPtr, this);
  }

  public void setCloseAmount(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseAmount_set(swigCPtr, this, value);
  }

  public double getCloseAmount() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseAmount_get(swigCPtr, this);
  }

  public void setPositionCost(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionCost_set(swigCPtr, this, value);
  }

  public double getPositionCost() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionCost_get(swigCPtr, this);
  }

  public void setPreMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PreMargin_set(swigCPtr, this, value);
  }

  public double getPreMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PreMargin_get(swigCPtr, this);
  }

  public void setUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_UseMargin_set(swigCPtr, this, value);
  }

  public double getUseMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_UseMargin_get(swigCPtr, this);
  }

  public void setFrozenMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenMargin_set(swigCPtr, this, value);
  }

  public double getFrozenMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenMargin_get(swigCPtr, this);
  }

  public void setFrozenCash(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenCash_set(swigCPtr, this, value);
  }

  public double getFrozenCash() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenCash_get(swigCPtr, this);
  }

  public void setFrozenCommission(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenCommission_set(swigCPtr, this, value);
  }

  public double getFrozenCommission() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FrozenCommission_get(swigCPtr, this);
  }

  public void setCashIn(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CashIn_set(swigCPtr, this, value);
  }

  public double getCashIn() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CashIn_get(swigCPtr, this);
  }

  public void setCommission(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_Commission_set(swigCPtr, this, value);
  }

  public double getCommission() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_Commission_get(swigCPtr, this);
  }

  public void setCloseProfit(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfit_set(swigCPtr, this, value);
  }

  public double getCloseProfit() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfit_get(swigCPtr, this);
  }

  public void setPositionProfit(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionProfit_set(swigCPtr, this, value);
  }

  public double getPositionProfit() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PositionProfit_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_SettlementPrice_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_SettlementID_get(swigCPtr, this);
  }

  public void setOpenCost(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenCost_set(swigCPtr, this, value);
  }

  public double getOpenCost() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OpenCost_get(swigCPtr, this);
  }

  public void setExchangeMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ExchangeMargin_set(swigCPtr, this, value);
  }

  public double getExchangeMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ExchangeMargin_get(swigCPtr, this);
  }

  public void setCombPosition(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombPosition_set(swigCPtr, this, value);
  }

  public int getCombPosition() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombPosition_get(swigCPtr, this);
  }

  public void setCombLongFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombLongFrozen_set(swigCPtr, this, value);
  }

  public int getCombLongFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombLongFrozen_get(swigCPtr, this);
  }

  public void setCombShortFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombShortFrozen_set(swigCPtr, this, value);
  }

  public int getCombShortFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CombShortFrozen_get(swigCPtr, this);
  }

  public void setCloseProfitByDate(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfitByDate_set(swigCPtr, this, value);
  }

  public double getCloseProfitByDate() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfitByDate_get(swigCPtr, this);
  }

  public void setCloseProfitByTrade(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfitByTrade_set(swigCPtr, this, value);
  }

  public double getCloseProfitByTrade() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_CloseProfitByTrade_get(swigCPtr, this);
  }

  public void setTodayPosition(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_TodayPosition_set(swigCPtr, this, value);
  }

  public int getTodayPosition() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_TodayPosition_get(swigCPtr, this);
  }

  public void setMarginRateByMoney(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MarginRateByMoney_set(swigCPtr, this, value);
  }

  public double getMarginRateByMoney() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MarginRateByMoney_get(swigCPtr, this);
  }

  public void setMarginRateByVolume(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MarginRateByVolume_set(swigCPtr, this, value);
  }

  public double getMarginRateByVolume() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MarginRateByVolume_get(swigCPtr, this);
  }

  public void setStrikeFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_StrikeFrozen_set(swigCPtr, this, value);
  }

  public int getStrikeFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_StrikeFrozen_get(swigCPtr, this);
  }

  public void setStrikeFrozenAmount(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_StrikeFrozenAmount_set(swigCPtr, this, value);
  }

  public double getStrikeFrozenAmount() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_StrikeFrozenAmount_get(swigCPtr, this);
  }

  public void setAbandonFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_AbandonFrozen_set(swigCPtr, this, value);
  }

  public int getAbandonFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_AbandonFrozen_get(swigCPtr, this);
  }

  public void setOptionValue(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OptionValue_set(swigCPtr, this, value);
  }

  public double getOptionValue() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_OptionValue_get(swigCPtr, this);
  }

  public void setMaintUseMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MaintUseMargin_set(swigCPtr, this, value);
  }

  public double getMaintUseMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MaintUseMargin_get(swigCPtr, this);
  }

  public void setMaintExchangeMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MaintExchangeMargin_set(swigCPtr, this, value);
  }

  public double getMaintExchangeMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_MaintExchangeMargin_get(swigCPtr, this);
  }

  public void setIndexSettlementPrice(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_IndexSettlementPrice_set(swigCPtr, this, value);
  }

  public double getIndexSettlementPrice() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_IndexSettlementPrice_get(swigCPtr, this);
  }

  public void setFixedMargin(double value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FixedMargin_set(swigCPtr, this, value);
  }

  public double getFixedMargin() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_FixedMargin_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_ExchangeID_get(swigCPtr, this);
  }

  public void setYdStrikeFrozen(int value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_YdStrikeFrozen_set(swigCPtr, this, value);
  }

  public int getYdStrikeFrozen() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_YdStrikeFrozen_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return riskuserapiJNI.CShfeFtdcRspInvestorPositionField_InvestUnitID_get(swigCPtr, this);
  }

  public CShfeFtdcRspInvestorPositionField() {
    this(riskuserapiJNI.new_CShfeFtdcRspInvestorPositionField(), true);
  }

}
