/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcExchangeOrderInsertErrorField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcExchangeOrderInsertErrorField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcExchangeOrderInsertErrorField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcExchangeOrderInsertErrorField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ParticipantID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_InstallID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_OrderLocalID_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return riskuserapiJNI.CShfeFtdcExchangeOrderInsertErrorField_ErrorMsg_get(swigCPtr, this);
  }

  public CShfeFtdcExchangeOrderInsertErrorField() {
    this(riskuserapiJNI.new_CShfeFtdcExchangeOrderInsertErrorField(), true);
  }

}
