/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.future.risk.api;

public class CShfeFtdcTradeParamField {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CShfeFtdcTradeParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CShfeFtdcTradeParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        riskuserapiJNI.delete_CShfeFtdcTradeParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    riskuserapiJNI.CShfeFtdcTradeParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return riskuserapiJNI.CShfeFtdcTradeParamField_BrokerID_get(swigCPtr, this);
  }

  public void setTradeParamID(char value) {
    riskuserapiJNI.CShfeFtdcTradeParamField_TradeParamID_set(swigCPtr, this, value);
  }

  public char getTradeParamID() {
    return riskuserapiJNI.CShfeFtdcTradeParamField_TradeParamID_get(swigCPtr, this);
  }

  public void setTradeParamValue(String value) {
    riskuserapiJNI.CShfeFtdcTradeParamField_TradeParamValue_set(swigCPtr, this, value);
  }

  public String getTradeParamValue() {
    return riskuserapiJNI.CShfeFtdcTradeParamField_TradeParamValue_get(swigCPtr, this);
  }

  public void setMemo(String value) {
    riskuserapiJNI.CShfeFtdcTradeParamField_Memo_set(swigCPtr, this, value);
  }

  public String getMemo() {
    return riskuserapiJNI.CShfeFtdcTradeParamField_Memo_get(swigCPtr, this);
  }

  public CShfeFtdcTradeParamField() {
    this(riskuserapiJNI.new_CShfeFtdcTradeParamField(), true);
  }

}
