DROP TABLE IF EXISTS INVESTOR_INSTRUMENT;
create table INVESTOR_INSTRUMENT(
    INVESTOR_NO VARCHAR(10) not null,
    INSTRUMENT_ID VARCHAR(10),
    STOP_WIN INT,
    STOP_LOSS INT,
    STATUS CHAR,
    TARGET DOUBLE,
    RETRACEMENT DOUBLE,
    HEDGING_TYPE CHAR,
    HEDGING_TIGGER DOUBLE,
    HEDGING_VOLUME INT,
    HEDGING_STOP_WIN DOUBLE,
    HEDGING_STOP_LOSS DOUBLE
);